version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/openjdk:latest
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}
      - run: ./gradlew check test javadoc jar
      - save_cache:
          paths:
            - ~/.gradle
            - ~/code/.gradle
          key: jars-{{ checksum "build.gradle" }}
      - store_artifacts:
          path: build/reports
          destination: reports
      - store_artifacts:
          path: build/docs
          destination: docs
      - store_artifacts:
          path: build/libs
          destination: libs
      - store_test_results:
          path: build/test-results