name: Publish

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-java@v6
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_CENTRAL_TOKEN
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Verify release version
        if: github.ref_type == 'tag'
        run: |
          TAG_VERSION="${GITHUB_REF_NAME#v}"
          POM_VERSION="$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)"
          
          if [[ "$TAG_VERSION" != "$POM_VERSION" ]]; then
            echo "Tag version ($TAG_VERSION) does not match POM version ($POM_VERSION)"
            exit 1
          fi

      - name: Set snapshot version
        if: github.ref_type != 'tag'
        run: |
          VERSION="$(git rev-parse --short HEAD)-SNAPSHOT"
          mvn versions:set -DnewVersion="$VERSION" -DgenerateBackupPoms=false

      - name: Publish
        run: mvn clean deploy
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
